### ISSUE TITLE
Skipping project because "Test execution should be skipped (-DskipTests)." while tests are in fact skipped.

### ISSUE THREAD

**Issue by ydolzhenko** [hcoles/pitest#1005]
`mvn -DskipTests=true verify -P mutation-incremental` doesn't run mutation tests with the following message:
```
[INFO] Skipping project because:
[INFO]   - Test execution should be skipped (-DskipTests).
```
Problem exists in `1.7.4` while `1.7.3` works just fine, so I guess #750 is to blame.

Attached you can find the pom.xml where problem can be reproduced.

[pom_xml.txt](https://github.com/hcoles/pitest/files/8332479/pom_xml.txt)

**Comment by hcoles** [comment]
@ydolzhenko 

Sorry, yes this is working as expected, although the impact of the change hadn't really been thought through. On balance, skipping running when `skipTest` is set does make sense since there are other ways of disabling surefire. There are also good arguments for it working as it did before, but rather than raking over them the intention is to leave the behavious as is.
