### ISSUE TITLE
Pitest killing surviving mutations when using `@BeforeEach` instead of `@BeforeAll`

### ISSUE THREAD

**Issue by Vyom-Yadav** [hcoles/pitest#1081]
Related PR: https://github.com/checkstyle/checkstyle/pull/12053
Related failing build: https://github.com/checkstyle/checkstyle/runs/7890740879?check_suite_focus=true
Build output:
```
Source File: "Violation.java"
Class: "com.puppycrawl.tools.checkstyle.api.Violation$Utf8Control"
Method: "newBundle"
Line Contents: "final String resourceName = toResourceName(bundleName, &quot;properties&quot;);"
Mutator: "org.pitest.mutationtest.engine.gregor.mutators.experimental.ArgumentPropagationMutator"
Description: "replaced call to com/puppycrawl/tools/checkstyle/api/Violation$Utf8Control::toResourceName with argument"
Line Number: 542
```

This particular mutation was being killed before using the `@BeforeAll` annotation. Even after using the `@BeforeAll` annotation, the test cases fail (mutation is technically **killed**) but pit shows it as survival.
The config is correct.

As a workaround if we use the `@BeforeEach` annotation, the mutation is correctly killed, it is just that using `@BeforeAll` doesn't kill the mutation when it should be killed as test cases fail individually.

`junit.version` : `5.9.0`
`pitest.junit5.plugin.version` : `1.0.0`
`pitest.accelerator.junit5.plugin.version` : `1.0.0`

Might be related to PRs and Issues:

- https://github.com/pitest/pitest-junit5-plugin/issues/64
- https://github.com/pitest/pitest-junit5-plugin/pull/65
- https://github.com/hcoles/pitest/issues/1036

**Comment by Vyom-Yadav** [comment]
@hcoles Feel free to ping me if you need any information regarding this, would be happy to provide :)

**Comment by hcoles** [comment]
@Vyom-Yadav 

From a quick scan through the code I think this is "working as expected", as the test suite has hit a wrinkle with how static state works with coverage based mutation systems.

Becuase this code is only run if there is no entry in the static BUNDLE_CACHE, the result of mutation testing will be highly dependent on the order in which tests are run. Adding or removing a test may completely change the order.

If 20 tests *could* execute the line of code, only the first one to run (and the first ones to run after each time the cache is cleared) will actually execute the code. Only these tests will be linked by coverage to the mutation, so pitest will only select from this reduced set when the mutant is active.

In the context of a BeforeAll this means that (assuming for a moment the test methods are executed in the order they are defined, which is not the case for JUnit)

```java
class Test {
   @BeforeAll
   void setup() {
     Foo.clearCache();
   }

  @Test
  void a() {
    Foo.doStuff();
  }

  @Test
  void b() {
    Foo.doStuff();
  }

  @Test
  void c() {
    Foo.doStuff();
  }
}
```

Only `a` will actually execute the cache-dependent code. Even if `b` or `c` can kill the mutant, pitest will never run them as they do not appear to execute the code.

When the mutation is recreated manually, the situation is different. All the tests will be run and the mutation will be detected by any test that is able to do so.

So, I think the issue here is that the code change has altered the order of the tests.

That said, one of the recent changes to how junit-5 works with pitest at the coverage stage is relevent, and results in the BeforeAlls being run once per class (as junit does it) instead of once per test method (as the junit 5 plugin had done it before) during the coverage stage (they are still run more frequently during the analysis stage).

I started to try and explain this behaviour here, but it was getting very long and complex. TL;DR a trade off had to be made, and on balance the approach where the BeforeAlls were run less frequently won. The downside is an increased number of surviving mutants in static state affected code. The upside is much faster analysis times and a reduction in eroneously failing tests due to corrupted static state.

**Comment by rnveach** [comment]
> Becuase this code is only run if there is no entry in the static BUNDLE_CACHE, the result of mutation testing will be highly dependent on the order in which tests are run.
> If 20 tests could execute the line of code, only the first one to run (and the first ones to run after each time the cache is cleared) will actually execute the code. Only these tests will be linked by coverage to the mutation, so pitest will only select from this reduced set when the mutant is active.

I thought I tested this by removing BUNDLE_CACHE and had it pretend the cache was always empty and always getting fresh values. It produced the same pitest results as if the cache was there. 

Now `sLocale` is also static and I did not do any tests with that. The original PR in question is changing the default locale. Maybe it is the "static" playing the role.

**Comment by rnveach** [comment]
@hcoles 
> Only these tests will be linked by coverage to the mutation, so pitest will only select from this reduced set when the mutant is active.

Is there a way to disable the "shrinking due to coverage" just to check this out and verify things?

**Comment by rnveach** [comment]
@hcoles I am playing around with the code and tests to try to atleast show in my mind what you are saying  and possibly in order to look at ways to change the tests.

I created a minimal version of this and I am still getting surviving mutant on the line in question though I can manually change the code and get a test failure.

Branch: https://github.com/rnveach/checkstyle/tree/pitest_1081

Profile pitest-api only runs the 1 test class. The 1 test class has been drastically reduced to just 1 test method. I removed most of the caching in the production code, which shouldn't matter with 1 test method.

`final String resourceName = toResourceName(bundleName, "properties");` still shows survivings. I can change this to `String resourceName = null;` and `String resourceName = "properties";` and the test fails.

**Comment by hcoles** [comment]
@rnveach I was about to take another look at this today, but from the edits in your comments it looks like you have tracked the issue down to something in the checkstyle codebase?

**Comment by rnveach** [comment]
Hey @hcoles . I appreciate you coming back to us. It was a cache issue, but it was a little more indepth than that. 

It is basically a misunderstanding between our code and `java.util.ResourceBundle`. We were putting our own cache, BUNDLE_CACHE, surrounding `ResourceBundle` which has its own internal cache. So we were basically double caching. Removing our cache did not fix the mutation like I was originally testing because of the 2nd level cache that, atleast, I was unaware of. `ResourceBundle`'s cache was never erased so like you said it populated during the start-up and remained.

The original code is very old so its unclear if `ResourceBundle` always had its own cache or if the original coders were unaware of this. They mentioned a speed improvement with our own cache.

I made a PR at https://github.com/checkstyle/checkstyle/pull/12102 to detail the issue and fix it. It is also killed some other pitest mutations. I am slowly trying to rework some of these classes from looking into this issue.
