### ISSUE TITLE
Report mutated source code?

### ISSUE THREAD

**Issue by ayaankazerouni** [hcoles/pitest#1090]
Hello,

I'm interested in working on a project for in-IDE mutation feedback. I'd like to report the actual mutated Java source code for surviving mutants in the feedback.

Right now, the CSV and other output formats report only the mutation operator that was used on a given line, but not the actual mutated source code. If a given mutator was applied only once to a given line, it's easy to work out what the mutation was. But if the same mutation operator was applied multiple times to the same line it becomes more difficult to tease out the specific mutations.

Is there some way to also emit the mutated source code in the output? I'd be happy to work on a PR for this, but I just wanted to check if this was feasible or possible with the byte code mutation. Thanks!

**Comment by ayaankazerouni** [comment]
Relatedly, [this page](http://pitest.org/faq/) mentions an `EXPORT` feature where mutations can be written to disk, and I see a `MutantExportInterceptor` that writes mutants to disk. But I don't see how to enable to this export during a PIT run using Maven or Gradle etc. Any pointers would be appreciated.

**Comment by hcoles** [comment]
As the mutations are created in the bytecode, the only way to get source for the mutant would be to decompile it. I have played around with this idea, but the results were not great.

Since we have the original source you could try and come up with some sort of mixed decompilation guided by original source scheme that might produce better results. This would be a non trivial project however.

If you want to try, there's no need to create a PR. Additional output formats can be created using the plugin system, so the project could be self contained.

To enable bytecode export you need to enable it's feature, eg

```
mvn -Dfeatures="+EXPORT" -Ppitest test
```

For maven.

**Comment by ayaankazerouni** [comment]
Thanks for the info! My student and I are planning to explore this. I'm closing this issue but will report back if anything comes of it.
