### ISSUE TITLE
InvertNegsMutator cannot work on constants

### ISSUE THREAD

**Issue by claudeyj** [hcoles/pitest#1132]
Hi, I sincerely admire Pitest tool. But recently I found a simple but not trivial miss case of InvertNegsMutator. The logic of implementation of this mutator is to remove the negation instruction in the bytecode. However, this mutator can not work on constants, e.g., -1 -> 1. This could be critical because negation operation is much less frequent in program compared with negative numbers. Therefore we should consider implementing this function.

**Comment by hcoles** [comment]
@claudeyj Although the documentation unhelpfully doesn't say so, this is by design. The mutator mutates only negation of variables, not constants.

The reason for this is that ICONST_M1 will be emitted in bytecode for a large number of compiler constructs. Mutating it will result in junk mutations that do not resemble errors in the source code.

Although it would be nice to also mutate -1 -> 1, it is not worth doing so at the cost if introducing junk mutations.

This is also the reason that the INLINE_CONSTANTS mutator is not enabled by default.

**Comment by claudeyj** [comment]
Thanks a lot!
