### ISSUE TITLE
How can i kill this mutation

### ISSUE THREAD

**Issue by hanshisan** [hcoles/pitest#1316]
Now i have some method like this
    ```
      public class TestBoolean {
  public Boolean testBoolean() {
    return Boolean.TRUE;
  }
}
    ```
and unit test 
        ```
         @Test
          void testBoolean() {
            assert new TestBoolean().testBoolean();
          }
     ```
repot notice NO_COVERAGE
<img width="927" alt="Snipaste_2024-03-17_23-28-24" src="https://github.com/hcoles/pitest/assets/44807194/0ce67e93-d2b9-4890-bfe9-7d138a977b1d">
As a new user of the pitest, or if I don't quite understand the true meaning of this prompt, how should I write this unit test

**Comment by hcoles** [comment]
It looks like there is a problem with your project setup. A status of NO_COVERAGE, means pitest didn't run any tests against the mutant. Since you have a test that covers the testBoolean method, this suggests there is something wrong in your build script preventing it from being picked up.

Once you've fixed that, you'll his a second problem. Your test most likely doesn't have a functioning assertion. The java `assert` keyword is not normally used for tests, and does nothing at all unless a runtime flag is set. Normally, tests use the build in junit assertion methods or a 3rd party library like assertj or hamcrest.

**Comment by hanshisan** [comment]
You're right, I made a basic mistake and misunderstood the meaning of NO_COVERAGE. When I changed ```assert``` to ```Assertions.assertTrue```, the problem was fixed.Thanks a lot!
