### ISSUE TITLE
Enable scmMutationCoverage goal to analyse files in the last commit

### ISSUE THREAD

**Issue by noroute** [hcoles/pitest#132]
For use in Continuous Integration scenarios it would be helpful to run mutation analysis only on the files changed last. At the moment this is only possible for uncommitted changes, which is only useful for analysis on developers' machines before pushing.

I'm not sure how difficult this would be since the Maven SCM Plugin does not seem to have a generic way to get hold of the files modified in a certain revision.

Since most CI mechanisms now the revision under consideration at runtime it would be ok if the revision would be a parameter and the SCM would not have to figure out the head revision.

**Comment by peome** [comment]
@noroute @hcoles  What's the status of this issue?

**Comment by cannehal** [comment]
+1 It would be really useful to have this feature for CI/CD

**Comment by mbj** [comment]
In mutant we have the `--since $commit_ref` in the CLI. It only selects mutation subjects that are in the diff between HEAD and the commit reference. Since the last commit can be selected via `HEAD~1`. On branches `--since master` is also great etc.

Before you implement this hardcoded against `HEAD~1` think about exposing a commit ref option instead.

We use the following `git log` CLI to detect changes: https://github.com/mbj/mutant/blob/master/lib/mutant/repository.rb#L35-L58

This should in theory be adaptable as an implementation vector, for a Pitest implementation of this feature.

**Comment by cannehal** [comment]
We can also get changelog with limit=1 parameter and extract filenames. Probably it should be merged from both sources - working copy and checked in changes. By using statuses to include we can choose execution of proper methods.

**Comment by cannehal** [comment]
This is working solution. Please free to review this code. Instead of if condition there can be i.e. some strategy but I would like to talk more about usage of new parameter, logic behind this etc.

**Comment by hcoles** [comment]
It looks good to me but I'd suggest a more natural interface would be to invert the logic and rename the parameter so you could do

```
mvn org.pitest:pitest-maven:scmMutationCoverage -DanalyseLastCommit
```

Does it still make sense to limit the analysis to certain a set of SCMFileStatus?

**Comment by cannehal** [comment]
It was my first choice. Will switch to it. I was also wandering about setting number of commits to analyze:
```
mvn org.pitest:pitest-maven:scmMutationCoverage -DanalyseLastCommits -Dllimit=1
```
 but for review (i.e Gerrit) only last commit will be useful. So by default when there is no limit parameter set it will 1.

Answering your question - what if removed, renamed classes will be added to analysis? This operations doesn't change anything in implementation. If we remove statuses limitation it will be added to analysis and will increase execution time which is bad (it is crucial to build fast for review changes).

**Comment by peome** [comment]
Hi, all. In which version will this issue be included?

**Comment by hcoles** [comment]
@peome This will be in 1.1.9

**Comment by peome** [comment]
@hcoles Thanks a lot!

**Comment by hcoles** [comment]
1.1.9 has now been released. Should sync over to maven central shortly.

**Comment by peome** [comment]
@hcoles Thanks again, Im going to update base pom with this update now!

**Comment by ileontiuc** [comment]
@cannehal is this feature mvn org.pitest:pitest-maven:scmMutationCoverage -DanalyseLastCommits -Dllimit=1  implemented already? 

currently:
-DanalyseLastCommit
or
-DanalyseLastCommits
runs the last commit

and any other variation like:
-DanalyseLastCommits -Dllimit=1
-DanalyseLastCommits -Dllimit=2
-DanalyseLastCommit -Dllimit=1
...
says there is "No modified files found - nothing to mutation test, analyseLastCommit=false"

Can you please advise? Thank you! :)

**Comment by KyleRogers** [comment]
@ileontiuc  I had a quick look at [ScmMojo](https://github.com/hcoles/pitest/blob/master/pitest-maven/src/main/java/org/pitest/maven/ScmMojo.java) because documentation at http://pitest.org is not up-to-date, unfortunately.

The property is named ```analyseLastCommit``` and is set to ```false``` by default. Thus ```-DanalyseLastCommit``` should change the behaviour, all other variants should apply default settings. I can't see a limit property there.

**Comment by ileontiuc** [comment]
@KyleRogers  thank you for your prompt reply!

**Comment by peome** [comment]
Yes, it is currently working

**Comment by ileontiuc** [comment]
@peome  can you please describe how to use this feature?
