### ISSUE TITLE
include mutated code in report

### ISSUE THREAD

**Issue by UrsMetz** [hcoles/pitest#146]
Currently the mutations are only described in textual form which makes it sometimes hard to find out which kind of mutation of the code is not covered by the tests. I think including the mutated code (like [mutant](https://github.com/mbj/mutant) does in the report in the terminal) for survived mutations in the HTML reports created by PIT could help with that. This would solve issue #145.

**Comment by hcoles** [comment]
I've finally had chance to take a look at this using procyon as @UrsMetz suggested.

Worryingly procyon doesn't look have been updated in a while.

http://www.benf.org/other/cfr/

Looks to be under active development, but is not easy to consume as it is closed source and not published to maven central.

I've put together a proof of concept in the decompilation branch

https://github.com/hcoles/pitest/tree/decompilation

This replaces the mutant description with a diff against the decompiled source.

There are a few issues

1. Currently broken for Java 6 (would need to either drop java 6 support or move into a plugin)
2. Adds a significant overhead. Decompilation will definitely need to be optional.
3. Formatting is terrible.

Not sure the best way to go on point 3. I suspect the best solution would be change the html report so that the decompilation info appears in a dedicated section rather than replacing the existing description.

If we do stick with replacing the description it probably needs some markup added to format it. Doing this is complicated by some tech debt - markdown in the descriptions is currently automatically escaped.

If anyone with better html skills than mine would like to play with this they are welcome.
