### ISSUE TITLE
Don't fail if there are no tests to mutate

### ISSUE THREAD

**Issue by ankon** [hcoles/pitest#182]
I added a new module in my maven project which only contains resources, and our "QA" build that runs pitest failed:

```
[INFO] --- pitest-maven:1.1.4:mutationCoverage (default-cli) @ persistency-model ---
[INFO] Found plugin : Default csv report plugin
[INFO] Found plugin : Default xml report plugin
[INFO] Found plugin : Default html report plugin
[INFO] Found plugin : Default limit mutations plugin
[INFO] Found shared classpath plugin : Default mutation engine
52:35 AM PIT >> INFO : Mutating from /home/bamboo/bamboo-agent-home/xml-data/build-dir/COL-QA-JOB1/persistency-model/target/classes
6:52:35 AM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
6:52:36 AM PIT >> INFO : Sending 0 test classes to slave
6:52:36 AM PIT >> INFO : Sent tests to slave
6:52:36 AM PIT >> INFO : Calculated coverage in 0 seconds.
6:52:36 AM PIT >> INFO : Created  0 mutation test units
[...]
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.1.4:mutationCoverage (default-cli) on project persistency-model: Execution default-cli of goal org.pitest:pitest-maven:1.1.4:mutationCoverage failed: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
```

This module doesn't have any java source files.

It would be really nice if the mutationCoverage goal would simply skip this project, just like the maven compiler/surefire/etc plugins do.

**Comment by hcoles** [comment]
This can be achieved by setting 

```
<configuration>
    <skip>true</skip>
</configuration>
```
For that module.

**Comment by fge** [comment]
@ankon has a point though; if there are no Java source files to begin with, mutations should not even be attempted ;)

**Comment by ankon** [comment]
@hcoles yes, and that is what I'm using now. So, on the level of severity: "minor annoyance", not "blocks anything". :)

For the case though it feels "wrong" to me to have to add this configuration, as it is "obvious" that there is no point in doing mutation coverage analysis of this project. This is why I mentioned the compiler and surefire plugins: you also configure those usually in the parent, but then don't expect to have to "unconfigure" them for modules that don't have java sources or junit tests.

**Comment by f9lz** [comment]
I have the same error! 

1:09:16 PM PIT >> INFO : Mutating from /Users/f9lz/Local/src/Scala-Testing-CodeCoverage/target/classes
1:09:16 PM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
1:09:17 PM PIT >> INFO : SLAVE : objc[36659]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_99.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_99.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be 
1:09:17 PM PIT >> INFO : SLAVE : used. Which one is undefined.

1:09:17 PM PIT >> INFO : Sending 0 test classes to slave
1:09:17 PM PIT >> INFO : Sent tests to slave
1:09:17 PM PIT >> INFO : SLAVE : 1:09:17 PM PIT >> INFO : Found  0 tests

1:09:17 PM PIT >> INFO : SLAVE : 1:09:17 PM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

1:09:17 PM PIT >> INFO : SLAVE : 1:09:17 PM PIT >> INFO : 0 tests received

1:09:17 PM PIT >> INFO : Calculated coverage in 0 seconds.
1:09:17 PM PIT >> INFO : Created  0 mutation test units
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

Where should i add this module because this module is created during build

**Comment by maxim-filkov** [comment]
One of possible workarounds is described [here](https://github.com/hcoles/pitest/issues/314).

**Comment by slaout** [comment]
+1

**Comment by Tony-Proum** [comment]
I think that this issue may be fixed without using a flag or other: it should be very painful to add a flag for each module on a project if the project contains one hundred or more submodules

**Comment by maxgabut** [comment]
Definitely fixed, [by this commit](https://github.com/hcoles/pitest/commit/e7658b7fa145abb546cd1f9954ca0357b426cf99).

**Comment by nithishbattina** [comment]
<plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>1.9.11</version>
                 <executions>
                     <execution>
                         <goals>
                             <goal>mutationCoverage</goal>
                         </goals>
                     </execution>
                 </executions>

                <dependencies>
                    <dependency>
                        <groupId>com.arcmutate</groupId>
                        <artifactId>pitest-kotlin-plugin</artifactId>
                        <version>1.3.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>1.2.1</version>
                    </dependency>
                </dependencies>


                <configuration>
                    <targetClasses>
                        <param>com.dbs.iprs.portfolio.services.*</param>
                    </targetClasses>
                    <targetTests>
                        <param>com.dbs.iprs.portfolio.services.*Test</param>
                    </targetTests>
                </configuration>
            </plugin>
            
            
            added my plugin here it is working java springboot project but not in kotlin springboot project and i am getting
             --- pitest-maven:1.9.11:mutationCoverage (default-cli) @ iprs-portfolio-service ---
[INFO] Skipping project because:
[INFO]   - Project has no tests, it is empty.
