### ISSUE TITLE
killing test name is incorrect when using TestNG

### ISSUE THREAD

**Issue by junghuk** [hcoles/pitest#238]
In output file, mutation.xml, some killing method name comes only _ (underbar).
For instance, joda-time,
```
<killingTest>org.joda.money.TestMoneyUtils_Money._</killingTest>
```

**Comment by hcoles** [comment]
This is the expected behaviour for TestNG.

Unlike JUnit tests pitest does not split TestNG tests down into their individual methods. Pitest is therefore only able to report that a test method within the test class killed the mutant, not which one.

It is possible to split TestNG tests down, but it turns out to be an expensive thing to do. Mutation testing generally works out faster if the whole TestNG test is run and the overhead of splitting is avoided.

**Comment by junghuk** [comment]
Thanks @hcoles for the explanation.
I understand your concern about the TestNG.

However, org.pitest.testng.TestNGAdapter already knows the name of killing test, even TestNG dose not split individual methods. The problem here, ResultCollector stores unnecessary description when TestNGAdapter.onStart and TestNGAdapter.onFinish. By emptying two methods, you can get correct killing method name,

```
//org.pitest.testng.TestNGAdapter

  @Override
  public void onFinish(final ITestContext arg0) {
  }

  @Override
  public void onStart(final ITestContext arg0) {
  }
```
