### ISSUE TITLE
Bug: tests with @RunWith do not end up in the line coverage

### ISSUE THREAD

**Issue by theangrydev** [hcoles/pitest#263]
This means they are never used for mutation testing.

This happens when using @RunWith(TableRunner.class) from https://github.com/bodar/yatspec

**Comment by theangrydev** [comment]
With verbose turned on, I can see that the correct runner seems to be invoked, because I can see the `FINE: Gathering coverage for test...` message with name set to the correct name of the test when the `com.googlecode.yatspec.junit.TableRunner` is used

**Comment by theangrydev** [comment]
And if I rewrite the test to still use `TableRuner` but not use a parametrised `@Table` test then the coverage is correctly picked up.

**Comment by hcoles** [comment]
Thanks for the PR.

As you've probably noticed the current logic is the wrong way round - there should really be a whitelist of runners that should be split rather than a blacklist of ones that shouldn't.

If I get chance I'll implement this change, otherwise I'll merge this in before the next release.

**Comment by hcoles** [comment]
Released in 1.10
