### ISSUE TITLE
How can I found what is broken?

### ISSUE THREAD

**Issue by caarlos0** [hcoles/pitest#279]
A test fails, like this:

```
2:30:13 PM PIT >> WARNING : Description [testClass=com.foo.BarTest, name=barMethod(com.foo.BarTest)] did not pass without mutation.
```

And that's about it of logs, even with `verbose` enabled. How can I find what is broken, and why? 

The test passes running it normally (`mvn clean install`, in the IDE, well, everywhere but pitest).

Furthermore, this should probably be an error log instead of warning. (#280)

**Comment by hcoles** [comment]
The problem is usually one of -

1. A test order dependency in the suite
2. A test being picked up by pitest that isn't normally run
3. An issue with a custom runner that pitest hasn't encountered before not splitting cleanly into subtests

A fix is needed for 3 (pitest currently contains a blacklist of runners to avoid splitting rather than the more sensible whitelist).

Unexpected tests can be spotted by scanning the log.

Most often is is point 1. Unfortunately test order dependencies are very difficult to debug (whether you are using pitest or not).

Perhaps a feature that writes out the lists of tests that will be run + their order to a text file would be useful?

**Comment by caarlos0** [comment]
> Perhaps a feature that writes out the lists of tests that will be run + their order to a text file would be useful?

yeah, that would probably be useful.
thanks 💃

**Comment by KyleRogers** [comment]
@hcoles 

I think it would be more useful to capture the output of the test (System.out/System.err ?) and write that to a file for later inspection. The current problem is that you can't find out what went wrong :-/

**Comment by hansjoachim** [comment]
I haven't tested it myself, but I see there's a pull request which would also log the stacktrace for failing test (#305). That might provide some more details to aid in debugging.
