### ISSUE TITLE
Negated Conditional called on for-each loop?

### ISSUE THREAD

**Issue by Ferocit** [hcoles/pitest#286]
Hi,

I don't really know if this is an issue or if I just don't understand the mutator correctly.

The code I have looks something like this:

```
final List<Order> orders = getOrdersFromSomewhere();
for (final Order order : orders) {
```

The Pit report is red and shows the following on the second line:

> 1. functionname : negated conditional -> SURVIVED

Is there something I don't get? I don't really know why it's using a negated conditional mutator here.

Version of PIT: 1.1.10

Thanks. :)

**Comment by hcoles** [comment]
This is a consequence of PIT mutating bytecode rather than source.

The bytecode for the for each loop looks something like

```
   INVOKEINTERFACE java/util/List.iterator ()Ljava/util/Iterator;
    ASTORE 2
   L2
    ALOAD 2
    INVOKEINTERFACE java/util/Iterator.hasNext ()Z
    IFEQ L3
    ALOAD 2
    INVOKEINTERFACE java/util/Iterator.next ()Ljava/lang/Object;
    // contents of the loop
    GOTO L2
   L3
```

So basically behind the scenes it is creating a iterator and checking the value of hasNext. While it's true it executes the loop by jumping to L2.

The conditional mutation is to the IFEQ L3 call that checks the return code of hasNext to exit the loop.

It would be nice if PIT could detect conditional statements generated by for each loops. I'm not sure that I've ever looked at this particular case, but in general distinguishing between bytecode produced by language features and bytecode that maps directly back to developer written code is either difficult or impossible.

**Comment by Ferocit** [comment]
Ah thanks a lot.

So in the case of a for-each loop, the mutator would either not iterate over any entries of the list, even though there would be entries or it would try to iterate, even though there are no entries (which should lead to an exception).

Is that correct?

**Comment by hcoles** [comment]
Yes, that sounds about right.

**Comment by Ferocit** [comment]
Great, got it. :+1:
