### ISSUE TITLE
Mutating Surefire POJO tests?

### ISSUE THREAD

**Issue by skapral** [hcoles/pitest#348]
Maven Surefire plugin supports so-called POJO tests, which doesn't require neither JUnit, nor TestNG for execution: http://maven.apache.org/surefire/maven-surefire-plugin/examples/pojo-test.html. Attempt to run mutations over these tests fails with the following message:
> Failed to execute goal org.pitest:pitest-maven:1.2.0:mutationCoverage (default) on project oo-atom: Execution default of goal org.pitest:pitest-maven:1.2.0:mutationCoverage failed: No test library found on classpath. PIT requires either JUnit 4 (but can run JUnit 3 tests) or TestNG

Do I have any options to overcome this issue without adding JUnit/TestNG to the classpath?

**Comment by hcoles** [comment]
Adding JUnit to the classpath won't solve the issues - pitest needs to support the test framework you are using and understand how to run the tests in order to perform a mutation analysis.

If you wish to analyse POJO tests you will need to write a plugin to support them. 

If you wish to try this you might find the example plugin for junit5 a useful reference.

https://github.com/tobiasstadler/pitest-junit5-plugin

**Comment by skapral** [comment]
Thanks for the reference. I'll check it.
