### ISSUE TITLE
No css in the report showed in jenkins (easy to fix)

### ISSUE THREAD

**Issue by sbuisson** [hcoles/pitest#403]
Hello:
Can you place the css of the html report in separated file?

Jenkins have a functionality who allow to archive some part of the workspace as "artifact" ( who will  easier to access than if they stay in the workspace- something tricky if you use pipeline-).

I want this functionality with pitest, in order to display the pitest-report
The issue is that jenkins forbid  "style-src self" for this archived file. (aka the css class definition in the html)

Can you place the css of the html report in separated file?

the stack trace:

> Refused to apply inline style because it violates the following Content Security Police directive: "style-src 'self'"

**Comment by hcoles** [comment]
Should be fixed in next release thanks to PR from @kiftio

**Comment by hcoles** [comment]
released in 1.2.5

**Comment by dalewking** [comment]
I am actually having the opposite problem. CSS is not loading in Jenkins because it is in a separate file. My issue is not the CSP but because the content of the Jenkins instance requires authentication and the call to get the CSS doesn't pass along the authentication cookies I get 403 error trying to retrieve the CSS. So I am looking for a solution to inline the CSS. Might be nice to make it an option whether to inline or not.
