### ISSUE TITLE
PIT is failing to identify all the available tests to run mutants against

### ISSUE THREAD

**Issue by scalderwood** [hcoles/pitest#416]
Hello,

I believe I've found an instance where PIT is not identifying all the available tests to run mutants against. This happens when running PIT against a Spring Boot application where there is a POST end point and CORS configuration for that end point. There are separate tests for the controller end point itself and also for the CORS configuration. If the controller end point test is not @Ignore, then PIT does not "see" the CORS configuration test. This does not appear to be a Spring Boot issue because if I manually mutate my code, then my tests fail as expected.

This case is reproducible with a small amount of code. I've done so in this git repo:
https://github.com/scalderwood/pitidentifyingtestissue

Copies of the PIT reports are here:
https://github.com/scalderwood/pitidentifyingtestissue/tree/master/pit-reports

If you build the project and then run the mutationCoverage goal, you will have the expected results (all mutants are killed). But if you comment out @Ignore in https://github.com/scalderwood/pitidentifyingtestissue/blob/master/src/test/java/com/scalderwood/pitest/testidentifying/ControllerTest.java and then re-build and re-run the mutationCoverage goal, then some mutants survive.

Please let me know if I can provide additional information.

**Comment by hcoles** [comment]
Thanks for raising this.

I've taken a quick look at example project you provided. I've not got my head around it yet (and I'm seeing different behaviour than you) buy I suspect the the issue is a test order dependency that affects the coverage targeting.

My (entirely unconfirmed) assumption is that the SecurityConfiguration is being constructed once per test suite and used by all the tests that require a spring configuration.

Enabling/disabling the ignore will change the order in which the tests run. Only the first test to run will cause the code in the SecurityConfiguration to execute - so the mutation test results may change as a different test will be targeted against the mutant.

As I'm typing this I'm less sure if this theory is coherent, however I'm not going to be able to dig much deeper for the next week or two. If you're able to dig further yourself and see if this makes sense that would help. The key question is how many instances of SecurityConfiguration will the test suite create, and when.

**Comment by hcoles** [comment]
After a play over lunch this looks to be a spring test issue.

Spring test keeps a cache of the context - only one (CGI modified) instance of the SecurityConfiguration class is constructed for the suite, then re-used for all tests.

If I mutate just the SecurityConfiguration class with

```
mvn org.pitest:pitest-maven:mutationCoverage -DtargetClasses=com.scalderwood.pitest.testidentifying.SecurityConfiguration -DtargetTests=com.scalderwood.* -Dverbose=true
```

Then all mutants survive as, although pit modifies the SecurityConfiguation class in memory the code that is actually run is a cgi modified version of the class that was instantiated earlier.

If I add `@DirtiesContext` to the test mutants start to be killed as this forces a refresh of the cache.

**Comment by scalderwood** [comment]
Thank you for looking into this so quickly and finding the issue. Following your suggestion, I've also been able to prove out that @DirtiesContext resolves the issue. It sounds like the necessary course of action in general is for any Spring test that uses the application context to also use @DirtiesContext. I wonder if it would make sense for Spring developers to have a wrapper around mutationGoal that first executed a process to add the @DirtiesContext to any test suite that uses the Spring application context and then executes mutationGoal. It is best practice to minimize the number of tests that use the Spring application context, so this is further motivation to only use it correctly. I'll have to think about this more.

It is coincidental timing. I was introducing my colleagues to PIT today and emphasized avoiding state in tests, and lo and behold that's the cause here.

Thank you again for your time.

**Comment by hcoles** [comment]
It would be nice if spring provided a way to completely disable context caching - from the point of view of pitest this would ideally be a system property. It would then be trivial for pitest to set this by default.

A scan through the issues suggests that exactly this has been suggested before, but closed as won't fix.

Something that almost, (but not quite) works has been implemented. The size of the cache can be set with`spring.test.context.cache.maxSize`.

https://jira.spring.io/browse/SPR-8055

Unfortunately it does not look to be possible to disable to cache completely as 0 will be interpreted as unbounded and negatives are disallowed.
