### ISSUE TITLE
collections mutators

### ISSUE THREAD

**Issue by Charmik** [hcoles/pitest#538]
Hello! I was wondering, have you ever thought about mutators for collections? Like add/remove, make .clear() after .add() or poll/peek/remove for Queue, first/list for Linked list or just omit collections methods if possible? do you think it will be helpful?

**Comment by maxgabut** [comment]
Hi !

**Comment by maxgabut** [comment]
Hi,

I don't know if it was ever considered or how hard it would be to implement such a mutator in pitest.

However, I don't think it would be really useful because existing mutators are already messing up with conditions, returns values, switches and the likes. So as long as there is some conditions in you code, you should get mutations similar to removing a call, or doing it too many time (and that would work for collections as well as for any other class).
