### ISSUE TITLE
Possibility to disable the Spinner

### ISSUE THREAD

**Issue by Vampire** [hcoles/pitest#642]
The pitest spinner competes with the Gradle progress display which results in rather ugly output artifacts.
It would be nice if the spinner could be disabled by some parameter except for enabling verbose output, so that the Gradle plugin could disable the spinner.

**Comment by dalewking** [comment]
I second this. I am actually invoking the command line pitest within gradle (because none of the gradle plugins support Kotlin Multiplatform Mobile) and the spinner is annoying, but I don't want verbose output.

**Comment by dalewking** [comment]
This is what I ended up doing in my gradle task to filter out the spinner:

        standardOutput = new FilterOutputStream(System.out) {
            boolean filtering = true

            @Override
            void write(int b) throws IOException {
                if (filtering)
                    switch (b) {
                        case 92: // \
                        case 124: // |
                        case 47: // /
                        case 45: // -
                        case 8: // Backspace
                            return
                        default:
                            filtering = false
                            break
                    }

                super.write(b)
            }
        }

**Comment by szpak** [comment]
> I am actually invoking the command line pitest within gradle (because none of the gradle plugins support Kotlin Multiplatform Mobile)

Are you reffering to https://github.com/koral--/gradle-pitest-plugin/issues/71 or support for "Kotlin Multiplatform Mobile" is something else (and then an issues describing the problem could be created)?

**Comment by dalewking** [comment]
[Kotlin Multiplatform Mobile](https://kotlinlang.org/lp/mobile/) is sort of a recent rebranding of part of the general [Kotlin Multiplatform](https://kotlinlang.org/docs/reference/multiplatform.html) to sort of separate out the use case of Kotlin -> JVM and Javascript from the mobile use case of Kotlin -> Android JVM and native iOS. This is separate from the use of case of just using [Kotlin in an Android project](https://kotlinlang.org/docs/reference/android-overview.html).

There are currently no plugins that exist for KMM. One could certainly be written and I'd be happy to share what I did to setup pitest using the command line in a KMM project if someone wants to write such a plugin or extend an existing plugin to support it. I didn't have time to write such a plugin and just went the command line route so we could start getting the benefits of pitest.

Regarding the actual topic of this issue, I was thinking that it would be nice instead of the 2 alternatives of Spinner or Verbose output that there was an intermediate option where you output lines like this to indicate activity:

    Testing mutations on class org.example.package.MyFooClass

Outputting entire lines of text should not interfere with normal gradle output

**Comment by szpak** [comment]
> There are currently no pitest plugins that exist for KMM

Thanks for you explanations @dalewking. To do not hijack this thread you may want to create a separate [issue](https://github.com/szpak/gradle-pitest-plugin/issues) with a link to a minimal Gradle project that shows the problem/error you get with the [gradle-pitest-plugin](https://github.com/szpak/gradle-pitest-plugin/issues) (a lack of Java plugin applied?). I don't know if it would be possible to add it in a sensible way (and time), but at least, it would be a central point for people subscribing to be noticed once there is a workaround/solution. Thanks.

**Comment by dalewking** [comment]
Wasn't trying to hijack the thread, I was merely trying to preemptively explain why I was using the command line version of pitest, since I know its use is discouraged.

**Comment by dalewking** [comment]
And applying the gradle-pitest-plugin does nothing since it only does something if you have Java plugin applied and doesn't give any error if you don't. Later on I was going to look at forking your plugin to add support but was more interested in getting the benefits of pitest than I was building a plugin.

**Comment by szpak** [comment]
> Wasn't trying to hijack the thread,

I was writing about myself, asking you about non-spinner related issues with KMM :-). Thanks for the ticked created.

**Comment by Vampire** [comment]
This is possible now with `--verbosity=NO_SPINNER`.
