### ISSUE TITLE
jvmArgs comma separation breaks for certain JVM arguments

### ISSUE THREAD

**Issue by davidburstromspotify** [hcoles/pitest#675]
Given PIT 1.4.2 (and quite likely other versions as well) it is impossible to pass any JVM arguments that themselves have comma separation. Such an example is `-XX:CompileCommand=command,method[,option]` In our case it's necessary to affect how JIT is performed and thus it doesn't work.

**Comment by plastic-karma** [comment]
We are having a similar problem in 1.6. We are trying to pass `-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005` to attach a debugger to the forked JVM, but it won't pick up the parts behind the comma correctly. It could be because of [OptionsParser](https://github.com/hcoles/pitest/blob/master/pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java#L208) which assumes that the input is comma separated.

I wonder how this can be fixed. Changing the semantic for `jvmArgs` and not treating comma as a separator is backwards-incompatabile.

Could a new commandline `jvmArg` be introduced with just a single value that will not be parsed?

**Comment by plastic-karma** [comment]
> Guess the only question is how it should behave if both parameters are supplied.

One option could be to just merge them all to a single list.

> If you've got time to put a pull request together and think about it, that would be great.

I'll do that. It is going to take a few days, but I am interested. :-)
