### ISSUE TITLE
pitest doesn't work correctly with constructors.

### ISSUE THREAD

**Issue by Troshchuk** [hcoles/pitest#709]
Hello,

I have found an issue. If some logic put into constructor pitest will be failed. It removes lines of code in constructor and it's failed due: 1. removed call to ... → SURVIVED. But it's covered by test and if remove lines manually tests are failed. The solution is use @PostConstruct instead of constructor. I created sample project to demonstrate: https://github.com/Troshchuk/pitest-bug . Could you please investigate an issue?

Thanks

**Comment by anatoliy-balakirev** [comment]
So basically if there are some calls to void methods in the constructor, pitest reports them as survived mutants even though they are covered with tests (and those tests are executed as part of the pitest's pipeline).

**Comment by hcoles** [comment]
@Troshchuk Thanks for the report and the minimal project that reproduces it (makes life hugely easier).

The problem is that AppMessageSource is a singleton, so the constructor is excecuted exactly once per jvm. The mutants are therefore never executed.

The only way pitest could robustly handle this would be to create a JVM per mutant, which would make mutation testing orders of magnitude slower. Unfortunately a trade off has to be made here.

This sort of issue can be avoided by writing pure unit tests that avoid spring extensions, autowiring and other magic. This usually also requires a change to the coding style used in the production code, so spring magic is constrained there also, and classes can be cleanly constructed in the absence of spring.

**Comment by anatoliy-balakirev** [comment]
@hcoles thanks for a quick response! Is it possible to at least log some warning / error for such cases? Is that info somehow available when mutants are executed? I mean is there something in the execution context (if there is such a thing at all), which will see that it's currently executed with spring and it tries to modify something within the constructor.

**Comment by hcoles** [comment]
If pitest could detect the situation it would filter out the mutants (as it does for the similar situation of static initiliazers).

Unfortuantely, for a spring singleton pitest would need to understand spring + how it is configured, and also check the entire test suite to check that something configured as a spring singleton was not constructed normally by the tests.

This is probably possible, but likely impractical given pitest would have to then track and understand every change made in a spring release.

In this particular case there is no reason for the test to use the spring extension and inject. The test could simply call new AppMessageSource and the mutants would then be killed.

**Comment by anatoliy-balakirev** [comment]
Ok, thanks. Yeah, that sounds like an overkill.

P.S. This particular case we already solved by moving that stuff from constructor to the dedicated init method + `@PostConstruct` (which probably makes more sense to do anyway).

**Comment by oorakci** [comment]
I have the same problem, I test controller classes in Spring Boot with the @WebMvcTest annotation. In this case, controller classes are instantiated as singleton, constructors are executed only once, that's why constructor mutations cannot be killed.

Is there a way to prevent generating mutations for constructors? I tried excludedMethods property for constructors, but it didn't work.

We aim for high mutation coverage, so I need to exclude false positives.

**Comment by oorakci** [comment]
I have excluded constructor mutations in controller classes by writing custom MutationInterceptorFactory.
