### ISSUE TITLE
Pitest causes "Tests failing without mutations" with Unknown property '$$pitCoverageProbes'

### ISSUE THREAD

**Issue by jwilmoth** [hcoles/pitest#711]
I have a test class that passes Junit execution with maven's sufefire plugin, but PiTest shows 10 of the 12 tests in that class failing before mutations.  In all failed cases there is an error with the class under test's use of [`org.apache.commons.beanutils.PropertyUtils.getProperty`](https://commons.apache.org/proper/commons-beanutils/apidocs/org/apache/commons/beanutils/PropertyUtils.html#getProperty-java.lang.Object-java.lang.String-)

`11:10:54 AM PIT >> INFO : MINION : rage.execute.CoverageWorker.run(CoverageWorker.java:51)
        at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:90)
Caused by: java.lang.NoSuchMethodException: Unknown property '$$pitCoverageProbes'`

Here's the related verison info:
- Apache beanutils 1.9.1
- Maven 3.6.3
- Java version: 11.0.5
- pitest-junit5-plugin.version: 0.10
- pitest-maven.version: 1.4.10

On a related note, I've added the test that Pitest reports as failing to the `excludedTestClasses` maven plugin config with a `excludedTestClass`, but with no success.  I also tried adding the class under test to the `excludedClasses` config, but also w/out success.  Happy to open a separate issue for this if this isn't user error :)

**Comment by hcoles** [comment]
It sounds like something, either in beanutils or (more likely) code using it, is iterating through all the fields of a class, but failing to filter out synthetic fields (or indeed static fields).

This is probably a bug in that code.

I'd guess that you encounter a similar issue when you run the code through other coverage systems such as jacoco?

Like jacoco, pit adds a field to every class that holds a boolean array indicating which probes have been hit. This is a very common way to gather coverage, the field need to be static, and are marked as synthetic. Code working with reflection should avoid synthetic fields.

The reason excludedClasses does not work here is that the issue is happened at the coverage stage, whereas the excludedClasses currently only applies at the mutation testing stage.

It would however make sense to avoid instrumenting classes that will not be mutated.

**Comment by jwilmoth** [comment]
Thank you!  https://commons.apache.org/proper/commons-lang/javadocs/api-3.9/org/apache/commons/lang3/reflect/FieldUtils.html#getAllFieldsList-java.lang.Class- does indeed return all fields, but filtering that with https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/Field.html#isSynthetic() resolved the issue.
