### ISSUE TITLE
-DskipTests Flag not working

### ISSUE THREAD

**Issue by cobaasta** [hcoles/pitest#750]
I know there is already a closed issue "Pit Maven Plugin Should Honor -DskipTests Flag #157", but the flag is not working, the command "mvn install -DskipTests" is still executing Pitest.

Affected Version org.pitest.pitest-maven.1.5.1

Btw.: The command "mvn install -DskipPitest"  works as expected!

**Comment by MosheElisha** [comment]
Try adding:

```
<configuration>
          <skipTests>true</skipTests>
</configuration>
```

From the docs:

```
Type: boolean
Default Value: false

honours common skipTests flag in a maven run
```

**Comment by rnveach** [comment]
@hcoles @marwin1991 
What is the proper way to skip test execution and just run pitest?

Checkstyle was hit with this at https://github.com/checkstyle/checkstyle/pull/11276#issuecomment-1030508925 .

When I remove the `test` and run straight `mvn clean org.pitest:pitest-maven:mutationCoverage` (Note this is also the command listed on https://pitest.org/quickstart/maven/ ), I get the error:
````
PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
PIT >> INFO : Incremental analysis reduced number of mutations by 0
PIT >> INFO : Created  0 mutation test units in pre scan
````

And when I use `mvn clean test org.pitest:pitest-maven:mutationCoverage`, it executes the test suite, which pitest will execute again itself as its startup process.

We were trying to avoid double work by excluding test runs and still wanting pitest to do its thing in its own run.

**Comment by marwin1991** [comment]
@hcoles @rnveach

Maybe we should reopen this issue and discus the problem, because from what I understand piTest should create mutation even if tests are not executed, as @rnveach mentioned above there is an command example in a documentation.

On the other hand we have this special flag `skipTests` in piTest configuration that everyone was using, and in addition
we have had #157 which was adding this funcionality.

IMO the main question is that: Is command `mvn clean org.pitest:pitest-maven:mutationCoverage` correct and piTest should generate mutations ?

**Comment by marwin1991** [comment]
@rnveach

I have made some test and it looks like, `mutationCoverage`  is not compiling test classes and that is why it is not finding mutations.

IMO you should use:
```
mvn clean test-compile org.pitest:pitest-maven:mutationCoverage
```

**Comment by hcoles** [comment]
Yes, the tests won't be compiled if you run just the pitest goal. I've updated the docs now to add test-compile.

Calling the goal directly requires minimal setup, but is not a great way to run pitest. I recomend creating a profile as discussed here.

https://blog.pitest.org/pitest-pr-setup/

This also shows one (slightly hacky) method of avoiding surefire also running, but binding pitest to test-compile instead of test.

A cleaner way is described here, although it requires more boilerplate.

https://stackoverflow.com/questions/14476757/disable-maven-plugins-when-using-a-specific-profile
