### ISSUE TITLE
Is it possible to only mutate jar file without any test execution? 

### ISSUE THREAD

**Issue by Marvinmw** [hcoles/pitest#830]
Is it possible to only mutate jar file without any test execution? I want to get different versions of jar file.

**Comment by StefanPenndorf** [comment]
Hi @Marvinmw !

there is a hardly documented export feature as of pitest 1.3.0. The export dumps all mutants into a directory structure, see #650.
To activate behavior +EXPORT must be added to the feature list. e.g,

```
mvn -Dfeatures=+EXPORT
```
(see #443)

**Comment by Marvinmw** [comment]
Hi, Much thanks.
But if I only have java jar file and do not have any info about the source code. Is it still possible?

**Comment by StefanPenndorf** [comment]
You've already closed the issue thus you might already have the answer to your last question.

> But if I only have java jar file and do not have any info about the source code. Is it still possible?

In theory, yes. Pitest mutates bytecode only. Thus for creating mutations bytecode will be sufficient. But Pitest also tries to map bytecode back to source code in order to report the correct line where a mutation survived. I haven't checked whether Pitest supports disabling source-code back-mapping but I doubt this is possible out of the box.
