### ISSUE TITLE
How to access mutants generated by PiTest?

### ISSUE THREAD

**Issue by alperen21** [hcoles/pitest#956]
Hello,

I would like to access the mutated versions of the code as a java file / binary file / etc. and I would be very pleased to learn which configurations and steps I should follow in order to do this.

Thank you in advance,

**Comment by hcoles** [comment]
Pitest mutates bytecode rather than source, so it is not possible to access mutated source files.

Adding `+EXPORT` to the feature string will however active writing the mutated bytecode to disk.

This functionality was originally developed as a plugin

https://github.com/pitest/export-plugin

But is now built into pitest.

**Comment by ayaankazerouni** [comment]
Great, thank you very much.
