### ISSUE TITLE
Can pitest be used with Java 17?

### ISSUE THREAD

**Issue by MariaSalim** [hcoles/pitest#964]
**Error:** Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 60

**Comment by szpak** [comment]
It would be much easier to address your problem knowing what PIT version you are trying to use and how (Gradle, Maven, ...).

**Comment by MariaSalim** [comment]
I am using plugin pitclipse version 2.1.2 in Eclipse 2021-09 release.

**Comment by szpak** [comment]
I don't know the Eclipse plugin, but first, please verify and under the hood, that plugin version uses some recent PIT version (e.g. 1.7.3). Earlier might not be JDK 17 compatible.

**Comment by krishnan-mani** [comment]
Error running pitest with Java 17, see below

```
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.7.3:mutationCoverage (default-cli) on project acler: Execution default-cli of goal org.pitest:pitest-maven:1.7.3:mutationCoverage failed: Coverage generation minion exited abnormally!
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : Oracle Corporation
[ERROR] Version : 17+35-2724
[ERROR] Uptime : 2032
[ERROR] Input -> 
[ERROR]  1 : -Dclassworlds.conf=/usr/local/Cellar/maven/3.8.4/libexec/bin/m2.conf
[ERROR]  2 : -Dmaven.home=/usr/local/Cellar/maven/3.8.4/libexec
[ERROR]  3 : -Dlibrary.jansi.path=/usr/local/Cellar/maven/3.8.4/libexec/lib/jansi-native
[ERROR]  4 : -Dmaven.multiModuleProjectDirectory=/Users/manik/development/foundations/dp-acler
[ERROR] BootClassPathSupported : false
```

I ran 
`$ mvn org.pitest:pitest-maven:mutationCoverage` and my `pom.xml` includes the plugin

```
<plugin>
                    <groupId>org.pitest</groupId>
                    <artifactId>pitest-maven</artifactId>
                    <version>LATEST</version>
</plugin>
```

**Comment by szpak** [comment]
@krishnan-mani Are you using it in the same project as Maria?

In your case:
> Coverage generation minion exited abnormally!

There could be some failing tests. Re-run the command with the verbose output (AFAIR `<verbose>true</verbose>`).

**Comment by krishnan-mani** [comment]
@szpak Thank you for a prompt response. 
I am not using this in the same project as Maria (as I see earlier in the thread).

I verified that there are no test failures, and running with verbose output reveals the following:

```
05:08:11 PIT >> FINE : System class path is /usr/local/Cellar/maven/3.8.4/libexec/boot/plexus-classworlds-2.6.0.jar
05:08:11 PIT >> FINE : Maximum available memory is 4096 mb
05:08:11 PIT >> FINE : Could not find java/lang/String on classpath for analysis. Falling back to classloader
05:08:11 PIT >> FINE : Could not find java/util/Map on classpath for analysis. Falling back to classloader
05:08:11 PIT >> FINE : Could not find java/lang/Object on classpath for analysis. Falling back to classloader
05:08:11 PIT >> FINE : Could not find java/util/List on classpath for analysis. Falling back to classloader
05:08:11 PIT >> FINE : Incremental analysis set 244 mutations to a status of NOT_STARTED
05:08:11 PIT >> INFO : Incremental analysis reduced number of mutations by 0
05:08:11 PIT >> INFO : Created  11 mutation test units in pre scan
05:08:11 PIT >> FINE : MINION : Installing PIT agent
05:08:11 PIT >> INFO : Sending 13 test classes to minion
05:08:11 PIT >> INFO : Sent tests to minion
05:08:11 PIT >> INFO : MINION : 05:08:11 PIT >> FINE : Expecting 13 tests classes from parent
05:08:11 PIT >> INFO : MINION : 05:08:11 PIT >> FINE : Tests classes received
05:08:11 PIT >> FINE : MINION : java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter
05:08:11 PIT >> FINE : MINION : 	at org.pitest.junit.JUnitCompatibleConfiguration.testUnitFinder(JUnitCompatibleConfiguration.java:54)
05:08:11 PIT >> FINE : MINION : 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
05:08:11 PIT >> FINE : MINION : 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
05:08:11 PIT >> FINE : MINION : 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
05:08:11 PIT >> FINE : MINION : 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
05:08:11 PIT >> FINE : MINION : 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
05:08:11 PIT >> FINE : MINION : 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
05:08:11 PIT >> FINE : MINION : 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
05:08:11 PIT >> FINE : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestConfiguration.makeFinder(PrioritisingTestConfiguration.java:61)
05:08:11 PIT >> FINE : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestConfiguration.<init>(PrioritisingTestConfiguration.java:20)
05:08:11 PIT >> FINE : MINION : 	at org.pitest.mutationtest.config.MinionSettings.getTestFrameworkPlugin(MinionSettings.java:38)
05:08:11 PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.createTestPlugin(CoverageMinion.java:168)
05:08:11 PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:132)
05:08:11 PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:82)
05:08:11 PIT >> FINE : MINION : Caused by: java.lang.ClassNotFoundException: org.junit.runner.manipulation.Filter
05:08:11 PIT >> FINE : MINION : 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
05:08:11 PIT >> FINE : MINION : 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
05:08:11 PIT >> FINE : MINION : 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
05:08:11 PIT >> FINE : MINION : 	... 14 more
05:08:11 PIT >> INFO : MINION : 05:08:11 PIT >> SEVERE : Error calculating coverage. Process will exit.
05:08:11 PIT >> INFO : MINION : java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter
05:08:11 PIT >> INFO : MINION : 	at org.pitest.junit.JUnitCompatibleConfiguration.testUnitFinder(JUnitCompatibleConfiguration.java:54)
05:08:11 PIT >> INFO : MINION : 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
05:08:11 PIT >> INFO : MINION : 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
05:08:11 PIT >> INFO : MINION : 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
05:08:11 PIT >> INFO : MINION : 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
05:08:11 PIT >> INFO : MINION : 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
05:08:11 PIT >> INFO : MINION : 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
05:08:11 PIT >> INFO : MINION : 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
05:08:11 PIT >> INFO : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestConfiguration.makeFinder(PrioritisingTestConfiguration.java:61)
05:08:11 PIT >> INFO : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestConfiguration.<init>(PrioritisingTestConfiguration.java:20)
05:08:11 PIT >> INFO : MINION : 	at org.pitest.mutationtest.config.MinionSettings.getTestFrameworkPlugin(MinionSettings.java:38)
05:08:11 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.createTestPlugin(CoverageMinion.java:168)
05:08:11 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:132)
05:08:11 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:82)
05:08:11 PIT >> INFO : MINION : Caused by: java.lang.ClassNotFoundException: org.junit.runner.manipulation.Filter
05:08:11 PIT >> INFO : MINION : 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
05:08:11 PIT >> INFO : MINION : 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
05:08:11 PIT >> INFO : MINION : 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
05:08:11 PIT >> INFO : MINION : 	... 14 more
05:08:11 PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.357 s
[INFO] Finished at: 2021-12-14T05:08:11Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.7.3:mutationCoverage (default-cli) on project acler: Execution default-cli of goal org.pitest:pitest-maven:1.7.3:mutationCoverage failed: Coverage generation minion exited abnormally!
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : Oracle Corporation
[ERROR] Version : 17+35-2724
[ERROR] Uptime : 2048
[ERROR] Input -> 
[ERROR]  1 : -Dclassworlds.conf=/usr/local/Cellar/maven/3.8.4/libexec/bin/m2.conf
[ERROR]  2 : -Dmaven.home=/usr/local/Cellar/maven/3.8.4/libexec
[ERROR]  3 : -Dlibrary.jansi.path=/usr/local/Cellar/maven/3.8.4/libexec/lib/jansi-native
[ERROR]  4 : -Dmaven.multiModuleProjectDirectory=/Users/manik/development/foundations/dp-acler
[ERROR] BootClassPathSupported : false
```

Note that I am using JUnit5 (Jupiter) for tests within the project.

**Comment by krishnan-mani** [comment]
Is there an update on this issue?

**Comment by szpak** [comment]
Do you by any change use JUnit 5 (Jupiter)?

**Comment by mathiascouste** [comment]
@krishnan-mani I got the same issue when bumping my project from Java 11 to 17.
I fixed it by changing some versions in the plugin:
![image](https://user-images.githubusercontent.com/3739271/148086112-2ad2757e-baf7-4ced-ae3a-b4aab0ea88d6.png)

Good luck !

**Comment by krishnan-mani** [comment]
thanks @mathiascouste 
I am able to run pitest with JUnit 5 on Java 17 with this plugin configuration.

**Comment by AnomalieXB-6783746** [comment]
Hey,
with the setup suggested by @mathiascouste I still don't get pitest to run.
I'm using `Java 17.0.1 2021-10-19 LTS` and maven as build tool as well.
I can't really make sense off the result off running with the verbose setting enabled, anybody an idea what could cause this?

`19:08:28 PIT >> FINE : System class path is <myPath>/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/home/valerio/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar
19:08:28 PIT >> FINE : Maximum available memory is 1960 mb
19:08:29 PIT >> FINE : Incremental analysis set 655 mutations to a status of NOT_STARTED
19:08:29 PIT >> INFO : Incremental analysis reduced number of mutations by 0
19:08:29 PIT >> INFO : Created  26 mutation test units in pre scan
19:08:29 PIT >> FINE : MINION : Installing PIT agent
19:08:29 PIT >> INFO : Sending 68 test classes to minion
19:08:29 PIT >> INFO : Sent tests to minion
19:08:30 PIT >> INFO : MINION : 19:08:30 PIT >> FINE : Expecting 68 tests classes from parent
19:08:30 PIT >> INFO : MINION : 19:08:30 PIT >> FINE : Tests classes received
19:08:30 PIT >> INFO : MINION : 19:08:30 PIT >> INFO : Checking environment
19:08:31 PIT >> FINE : MINION : java.lang.NoSuchMethodError: 'org.junit.platform.engine.ConfigurationParameters org.junit.platform.launcher.TestPlan.getConfigurationParameters()'
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.listeners.UniqueIdTrackingListener.testPlanExecutionStarted(UniqueIdTrackingListener.java:139)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$testPlanExecutionStarted$4(TestExecutionListenerRegistry.java:82)
19:08:31 PIT >> FINE : MINION : 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:51)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:27)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.testPlanExecutionStarted(TestExecutionListenerRegistry.java:82)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:149)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.junit5.JUnit5TestUnitFinder.findTestUnits(JUnit5TestUnitFinder.java:79)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestUnitFinder.findTestUnits(PrioritisingTestUnitFinder.java:19)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:57)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:159)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:135)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:82)
19:08:31 PIT >> INFO : MINION : 19:08:31 PIT >> SEVERE : Error calculating coverage. Process will exit.
19:08:31 PIT >> INFO : MINION : java.lang.NoSuchMethodError: 'org.junit.platform.engine.ConfigurationParameters org.junit.platform.launcher.TestPlan.getConfigurationParameters()'
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.listeners.UniqueIdTrackingListener.testPlanExecutionStarted(UniqueIdTrackingListener.java:139)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$testPlanExecutionStarted$4(TestExecutionListenerRegistry.java:82)
19:08:31 PIT >> INFO : MINION : 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:51)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:27)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.testPlanExecutionStarted(TestExecutionListenerRegistry.java:82)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:149)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.junit5.JUnit5TestUnitFinder.findTestUnits(JUnit5TestUnitFinder.java:79)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestUnitFinder.findTestUnits(PrioritisingTestUnitFinder.java:19)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:57)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:159)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:135)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:82)
19:08:31 PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR`

Could this be related to the presence of the junit-vintage-engine?
Thanks in advance :)

**Comment by AnomalieXB-6783746** [comment]
Hey,
I followed the setup suggested by mathiascouste, yet I face a comparable error when trying to run pitest with Junit5.
I'm using `java 17.0.1` and maven as build-tool.
When trying to run pitest with the verbose option enabled I get the following output:
```
19:08:28 PIT >> FINE : System class path is <myPath>/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/plugins/maven/lib/maven3/boot/plexus-classworlds.license:<myPath>/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar
19:08:28 PIT >> FINE : Maximum available memory is 1960 mb
19:08:29 PIT >> FINE : Incremental analysis set 655 mutations to a status of NOT_STARTED
19:08:29 PIT >> INFO : Incremental analysis reduced number of mutations by 0
19:08:29 PIT >> INFO : Created  26 mutation test units in pre scan
19:08:29 PIT >> FINE : MINION : Installing PIT agent
19:08:29 PIT >> INFO : Sending 68 test classes to minion
19:08:29 PIT >> INFO : Sent tests to minion
19:08:30 PIT >> INFO : MINION : 19:08:30 PIT >> FINE : Expecting 68 tests classes from parent
19:08:30 PIT >> INFO : MINION : 19:08:30 PIT >> FINE : Tests classes received
19:08:30 PIT >> INFO : MINION : 19:08:30 PIT >> INFO : Checking environment
19:08:31 PIT >> FINE : MINION : java.lang.NoSuchMethodError: 'org.junit.platform.engine.ConfigurationParameters org.junit.platform.launcher.TestPlan.getConfigurationParameters()'
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.listeners.UniqueIdTrackingListener.testPlanExecutionStarted(UniqueIdTrackingListener.java:139)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$testPlanExecutionStarted$4(TestExecutionListenerRegistry.java:82)
19:08:31 PIT >> FINE : MINION : 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:51)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:27)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.testPlanExecutionStarted(TestExecutionListenerRegistry.java:82)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:149)
19:08:31 PIT >> FINE : MINION : 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.junit5.JUnit5TestUnitFinder.findTestUnits(JUnit5TestUnitFinder.java:79)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestUnitFinder.findTestUnits(PrioritisingTestUnitFinder.java:19)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:57)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:159)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:135)
19:08:31 PIT >> FINE : MINION : 	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:82)
19:08:31 PIT >> INFO : MINION : 19:08:31 PIT >> SEVERE : Error calculating coverage. Process will exit.
19:08:31 PIT >> INFO : MINION : java.lang.NoSuchMethodError: 'org.junit.platform.engine.ConfigurationParameters org.junit.platform.launcher.TestPlan.getConfigurationParameters()'
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.listeners.UniqueIdTrackingListener.testPlanExecutionStarted(UniqueIdTrackingListener.java:139)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$testPlanExecutionStarted$4(TestExecutionListenerRegistry.java:82)
19:08:31 PIT >> INFO : MINION : 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyTestExecutionListeners(TestExecutionListenerRegistry.java:51)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$100(TestExecutionListenerRegistry.java:27)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.testPlanExecutionStarted(TestExecutionListenerRegistry.java:82)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:149)
19:08:31 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.junit5.JUnit5TestUnitFinder.findTestUnits(JUnit5TestUnitFinder.java:79)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.mutationtest.config.PrioritisingTestUnitFinder.findTestUnits(PrioritisingTestUnitFinder.java:19)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:57)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:159)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:135)
19:08:31 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:82)
19:08:31 PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
``` 
It seems to be a problem with finding the tests, but as stated in line 8 there are 68 classes found to test.
Might this be due to the presence of the junit-vintage-engine?

I'd be glad for any ideas, thanks in advance :)

**Comment by szpak** [comment]
@AnomalieXB-6783746 Please analyze your PIT execution classpath and ensure that there is JUnit Platform 1.8.x (not 1.7.x).

**Comment by AnomalieXB-6783746** [comment]
> @AnomalieXB-6783746 Please analyze your PIT execution classpath and ensure that there is JUnit Platform 1.8.x (not 1.7.x).

Thank you for the hint @szpak , after finally finding time to try to fix the issue it really was due to the JUnit version not being up to date. Works fine now!

**Comment by szpak** [comment]
@MariaSalim Do you still experience the problem? If yes, I propose to report it directly to the Eclipse plugin maintainer with request to bump dependencies (and probably linking to that thread). PIT itself is capable of running with JDK 17.

**Comment by MariaSalim** [comment]
@szpak, I wasn't able to find a fix for it at the time I opened this issue but, I managed to use it with Maven. I will close the issue. Thank you!

**Comment by antemo** [comment]
Hi
We are moving our project to JDK17 and pitest-maven plugin is failing our build due to failed mutation score.
There are no logs to explain why this is happening (even with -X flag and -Dverbose option), so it's hard to figure out why is this happening.

Initially we were using plugin version 1.4.9, but I tried updating to 1.7.4 to no help.
We are also using junit 4.12 in this project, which I tried bumping to 4.13.2 also to no effect.

**Comment by hcoles** [comment]
@antemo 

By "failing due to failed mutation score" do you mean you have set the build to break if the score drops below a certain number? If so you will need to compare the reports from running on <17 and 17 and identify which mutants now survive which were killed (or filtered out before).

If you've made changes to the code as part of the change to 17, these additional surivors may be legitimate. If not, it is possible that due to changes in the bytecode that the compiler produces for 17 pitest is failing to filter mutants (eg inlined code from try catch blocks) that it did before. Or it could be something else. Either way, if you identify the additional surviving mutants and create a new issue with a minimal example project that reproduces the issue, I can take a look.

**Comment by antemo** [comment]
We didn't make any code changes for JDK17. Or to be more exact, we still have our JDK11 build and it's passing.

And yes, our build has threshold that seems to fail for JDK17.
I'll try to make the comparison, but I'm not sure if I'll be able to make example project as I can't share any of the our code.

With only cursory check, this seems to be the biggest offender (most survivors):
> org.pitest.mutationtest.engine.gregor.mutators.returns.EmptyObjectReturnValsMutator
>> Generated 17 Killed 0 (0%)
> KILLED 0 SURVIVED 13 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 4

**Comment by hcoles** [comment]
@antemo 

An example doesn't need to contain any of your actual code. It should contain the simplest possible code that demonstrates the issue.
